### ISSUE TITLE
"https://raw.githubusercontent.com/designgears/totk-tiles/"  this url is not accessible

### ISSUE THREAD

**Issue by hxyfj** [designgears/totk-maps#1]

**Comment by designgears** [comment]
The tile repo is private until the review embargo is lifted, otherwise nintendo will have it removed.

**Comment by hxyfj** [comment]
So will all this content be released on github after 5.12?
May I take the liberty to ask, could you share some maps with me via email? I want to see the whole map

**Comment by designgears** [comment]
No, sorry, I don't want to risk the work I've done getting nuked by nintendo.
