### ISSUE TITLE
When cloning the project and opening it, the options are not displayed

### ISSUE THREAD

**Issue by jeluchu** [designgears/totk-maps#2]
Hi, I've been reviewing the project, but when I view it locally, the options menu in the top right corner is not shown, I show you below the images so that you can see the problem more clearly.

This is a image from https://explorezelda.com/#5/-1286.987/424.213:

![Captura de Pantalla 2023-06-08 a las 0 29 07](https://github.com/designgears/totk-maps/assets/32357592/2adb1552-18e7-4421-b265-1d08f465e72a)

And this image is from local:

![Captura de Pantalla 2023-06-08 a las 0 29 48](https://github.com/designgears/totk-maps/assets/32357592/9755d263-7bbd-4fee-819e-5dd4eae8f1a2)

**Comment by pratikbaid3** [comment]
Same here. Also, where are you getting the marker coordinates from.

**Comment by jeluchu** [comment]
@pratikbaid3 Checking through the browser console I found this link that leads to a json of data, most likely to get the points from there: https://explorezelda.com/data.json?_=1686208274804

**Comment by pratikbaid3** [comment]
Got it @jeluchu. Thanks

**Comment by pratikbaid3** [comment]
@jeluchu do you have any insight as to how the in-game coordinates are being converted to latlng?

**Comment by designgears** [comment]
@jeluchu I don't have the coordinates data in the repo just yet, still working thru some issues, sky markers on the surface, and some markers not close enough to where I'd like them (dungeon markers in the sky for example). Some of them multiple locations depending on the zoom in game. 

Feel free to use those from the site, but it does contain issues stated above.

**Comment by designgears** [comment]
Uploaded the marker data to the repo.
