### ISSUE TITLE
Possibility to improve map design elements

### ISSUE THREAD

**Issue by jeluchu** [designgears/totk-maps#3]
Include the game icons corresponding to each map:

![Captura de Pantalla 2023-06-08 a las 0 48 21](https://github.com/designgears/totk-maps/assets/32357592/6a835670-b5bc-4638-a9e2-5b273f316784)

Or include custom icons for items displayed within the map to make it more visual:

![Captura de Pantalla 2023-06-08 a las 0 49 01](https://github.com/designgears/totk-maps/assets/32357592/e17aa4b6-7754-4dc0-b405-a3c77d5c4a80)

I don't know if you are planning to do this, but anyway, how could you customise the icons that are displayed when you select any item instead of the circles as they are currently?

**Comment by designgears** [comment]
It's in the pipeline, the current version is just a working version that doesn't look pretty. The menu is based on leaflet-groupedlayercontrol, there were lots of issues I had to fix, you can checkout the fork [here](https://github.com/designgears/leaflet-groupedlayercontrol).

The icons for each marker type are also planned, the circles are placeholders until I get there. I have the code written to do it already, all canvas based, just need to start pulling images from the game data.
