### ISSUE TITLE
What is the coordinate system being used

### ISSUE THREAD

**Issue by pratikbaid3** [designgears/totk-maps#4]
Hi,

I am trying to understand the coordinate system being used and was also wondering if you have a list of marker coordinates for the map. I couldn't find that in the source code

**Comment by pratikbaid3** [comment]
Hi @designgears. I was going through the JSON created by you and I found this
```json
{
            "type": "Feature",
            "properties": {
                "id": 384829,
                "title": "Lookout Landing Skyview Tower",
                "category": "Locations",
                "subcat": "Skyview Tower",
                "description": "",
                "map": "Surface",
                "color": "#e81022",
                "hash": "17714356898717423783",
                "gyaml": "Tower01",
                "position": "-0299 | 0124 | 0143",
                "elevation": 123.941
            },
            "geometry": {
                "type": "Point",
                "coordinates": [
                    -298.85,
                    142.85
                ]
            }
        },
```
        
I am curious as to how you converted the in-game coordinates to your own coordinate system. It will be helpful if you could elaborate of the logic used. I am trying to convert these into raster coordinate systems

ie: How did [-0299,0124] become [-298.85,142.86]

**Comment by designgears** [comment]
@pratikbaid3 I'm using the coordinates almost directly from the game files, the only difference is that I'm inverting the polarity on the Y axis. 

The in-game "position" in the json is rounded off and zero padded to the left versions of the "coordinates" and "elevation" arranged in the same order as they appear in game.

X | Y | Z _(elevation)_
-298.85 | 123.941 | 142.85
-0299 | 0124 | 0143

I also have a custom projection based on CRS.Simple.
https://github.com/designgears/totk-maps/blob/ca2ab4c21d3fc915e353c97430bd313264fc210e/index.html#L174-L183

It uses a simple transformation matrix to move the center position from top left to center.
![image](https://github.com/designgears/totk-maps/assets/799451/dfe53edc-4412-41b7-a3d1-2dcd0990689b)

And scales it to match, so the 3 in game pixels become 1 map unit.
![image](https://github.com/designgears/totk-maps/assets/799451/34831f76-db28-4a75-bc07-69c906483cd4)

If you're using raster I think you just need to map.project() them using the zoom level where [units-per-pixel](https://github.com/designgears/totk-map-assets/blob/dc05e4ad94f5735db80f51a387c551d658b456cf/tiles/ground/tilemapresource.xml#LL18C73-L18C73) is 1.

**Comment by designgears** [comment]
Updated the position data, I now round the coordinates to whole numbers as well to avoid subpixel rendering issues on canvas.
